# Generated by Django 5.2.3 on 2025-07-12 16:29

import django.db.models.deletion
import innerlyapp.models.Profissionais
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concelho', models.CharField(choices=[('CRM', 'Concelho Regional de Medicina'), ('CRP', 'Concelho Regional de Psicologia')], max_length=3)),
                ('regiao', models.CharField(max_length=2)),
                ('numeroRegistro', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(blank=True, max_length=254, null=True)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(default='unknow', max_length=254)),
                ('biografia', models.CharField(blank=True, default='Olá estou no innerly!', max_length=254, null=True)),
                ('senha', models.CharField(max_length=254)),
                ('codigo_acompanhamento', models.CharField(default=innerlyapp.models.Profissionais.generate_code, max_length=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(blank=True, max_length=254, null=True)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(default='unknow', max_length=254)),
                ('biografia', models.CharField(blank=True, default='Olá estou no innerly!', max_length=254, null=True)),
                ('senha', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAceita', models.BooleanField(default=False)),
                ('dataSolicitacao', models.DateField(auto_now_add=True)),
                ('menssagem_solicitacao', models.TextField(default='')),
                ('estado', models.CharField(choices=[('aguardando', 'em andamento'), ('recusada', 'solicitação recusada'), ('aceita', 'solicitação aceita')], default='aguardando', max_length=254)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.profissional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitacoes',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueHumor', models.SmallIntegerField()),
                ('dataRegistro', models.DateField()),
                ('anotacao', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAtivo', models.BooleanField(default=True)),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.profissional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
            options={
                'verbose_name_plural': 'Acompanhamentos',
            },
        ),
    ]
