# Generated by Django 5.2.3 on 2025-07-04 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concelho', models.CharField(choices=[('CRM', 'Concelho Regional de Medicina'), ('CRP', 'Concelho Regional de Psicologia')], max_length=3)),
                ('regiao', models.CharField(max_length=2)),
                ('numeroRegistro', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(blank=True, max_length=254, null=True)),
                ('nascimento', models.DateField()),
                ('senha', models.CharField(max_length=254)),
            ],
        ),
    ]
