# Generated by Django 5.2.3 on 2025-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_pic_value',
            field=models.IntegerField(default=0),
        ),
    ]
