# Generated by Django 5.2.3 on 2025-06-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueHumor', models.SmallIntegerField()),
                ('dataRegistro', models.DateField()),
                ('anotacao', models.TextField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
        ),
    ]
