# Generated by Django 5.2.3 on 2025-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='estado',
            field=models.CharField(choices=[('aguardando', 'em andamento'), ('recusada', 'solicitação recusada'), ('aceita', 'solicitação aceita')], default='aguardando', max_length=254),
        ),
    ]
