# Generated by Django 5.2.3 on 2025-07-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0002_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
