# Generated by Django 5.2.3 on 2025-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0002_usuario_profile_pic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='profile_pic_value',
            field=models.IntegerField(default=0),
        ),
    ]
