# Generated by Django 5.2.3 on 2025-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0002_alter_autorizacao_options_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='numeroRegistro',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
