# Generated by Django 5.2.3 on 2025-07-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0003_alter_profissional_numeroregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(blank=True, default='Olá estou no innerly!', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(default='unknow', max_length=254),
        ),
    ]
