# Generated by Django 5.2.3 on 2025-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0003_profissional_profile_pic_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='innerlyapp.atividade'),
        ),
    ]
