# Generated by Django 5.2.3 on 2025-07-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0003_alter_profissional_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAtiva', models.BooleanField(default=True)),
                ('idProfissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.profissional')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
        ),
    ]
