# Generated by Django 5.2.3 on 2025-07-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0004_usuario_biografia_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='biografia',
            field=models.CharField(blank=True, default='Olá estou no innerly!', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='genero',
            field=models.CharField(default='unknow', max_length=254),
        ),
    ]
